---

- name: Create stacks directory
  ansible.builtin.file:
    path: /opt/stacks
    state: directory
    mode: '0750'

- name: Create stacks directory
  ansible.builtin.file:
    path: /opt/dockge
    state: directory
    mode: '0750'

- name: Create compose file for dockge
  ansible.builtin.template:
    src: templates/compose.yml.j2
    dest: /opt/dockge/compose.yaml
    mode: '640'
  notify:
    - Compose down
    - Compose up
